# Generated by Django 3.0.8 on 2020-07-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission_id',
        ),
        migrations.AddField(
            model_name='role',
            name='permission_id',
            field=models.ManyToManyField(null=True, to='users.Permission', verbose_name='权限'),
        ),
    ]
