# Generated by Django 3.0.8 on 2020-07-23 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200722_1100'),
        ('users', '0003_auto_20200723_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='name',
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.MenuClass', verbose_name='所属一级菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.LeftMenu', verbose_name='所属二级菜单'),
        ),
    ]
