# Generated by Django 3.0.8 on 2020-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200723_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色名称'),
        ),
    ]
