# Generated by Django 3.0.8 on 2020-07-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeftMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('sort', models.IntegerField(verbose_name='显示顺序')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='图标')),
                ('url', models.CharField(default='/', max_length=256, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '左侧菜单',
            },
        ),
    ]
