# Generated by Django 3.0.8 on 2020-07-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200721_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftmenu',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图标'),
        ),
    ]
