# Generated by Django 3.0.8 on 2020-07-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200721_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='分类名称')),
                ('sort', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '菜单分类',
            },
        ),
        migrations.RemoveField(
            model_name='leftmenu',
            name='icon',
        ),
        migrations.AddField(
            model_name='leftmenu',
            name='_class',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cms.MenuClass', verbose_name='所属分类'),
        ),
    ]
